# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto_message.proto\x12\x07globant\"\x1e\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03job\x18\x02 \x01(\t\",\n\nDepartment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ndepartment\x18\x02 \x01(\t\"c\n\x0eHired_employee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\t\x12\x15\n\rdepartment_id\x18\x04 \x01(\x05\x12\x0e\n\x06job_id\x18\x05 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOB._serialized_start=32
  _JOB._serialized_end=62
  _DEPARTMENT._serialized_start=64
  _DEPARTMENT._serialized_end=108
  _HIRED_EMPLOYEE._serialized_start=110
  _HIRED_EMPLOYEE._serialized_end=209
# @@protoc_insertion_point(module_scope)
